name: compile and unit test on native arch
on:
  push:
    branches:
      - sles15-sp2
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os: [buster, jessie, leap-15.2]
        arch: ['']
    container: mwilck/multipath-build-${{ matrix.os }}${{ matrix.arch }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build and test
        run: make test
